#############################################################################
# Makefile for building: q4wine
# Generated by qmake (2.01a) (Qt 4.4.2) on: Fri Dec 12 15:13:51 2008
# Project:  q4wine.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile q4wine.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DDEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -Isrc/gui -Isrc/core -Isrcs -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/qt4 -lQtSql -L/usr/lib/mysql -L/usr/lib/qt4 -lQtGui -L/usr/X11R6/lib -lpng -lSM -lICE -lXrender -lXrandr -lfreetype -lfontconfig -lXext -lX11 -lQtNetwork -lQtCore -lz -lm -lrt -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/gui/run.cpp \
		src/main.cpp \
		src/core/registry.cpp \
		src/core/winebinlauncher.cpp \
		src/gui/about.cpp \
		src/gui/appsettings.cpp \
		src/gui/iconsettings.cpp \
		src/gui/iconsview.cpp \
		src/gui/mainwindow.cpp \
		src/gui/prefixsettings.cpp \
		src/gui/process.cpp \
		src/gui/wizard.cpp moc_winebinlauncher.cpp \
		moc_about.cpp \
		moc_appsettings.cpp \
		moc_iconsettings.cpp \
		moc_iconsview.cpp \
		moc_mainwindow.cpp \
		moc_prefixsettings.cpp \
		moc_process.cpp \
		moc_run.cpp \
		moc_wizard.cpp \
		qrc_k4wine.cpp
OBJECTS       = run.o \
		main.o \
		registry.o \
		winebinlauncher.o \
		about.o \
		appsettings.o \
		iconsettings.o \
		iconsview.o \
		mainwindow.o \
		prefixsettings.o \
		process.o \
		wizard.o \
		moc_winebinlauncher.o \
		moc_about.o \
		moc_appsettings.o \
		moc_iconsettings.o \
		moc_iconsview.o \
		moc_mainwindow.o \
		moc_prefixsettings.o \
		moc_process.o \
		moc_run.o \
		moc_wizard.o \
		qrc_k4wine.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		q4wine.pro
QMAKE_TARGET  = q4wine
DESTDIR       = 
TARGET        = q4wine

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_About.h ui_AppSettings.h ui_IconSettings.h ui_IconsView.h ui_MainWindow.h ui_PrefixSettings.h ui_Process.h ui_Run.h ui_Wizard.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: q4wine.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/libQtSql.prl \
		/usr/lib/qt4/libQtCore.prl \
		/usr/lib/qt4/libQtGui.prl \
		/usr/lib/qt4/libQtNetwork.prl
	$(QMAKE) -unix -o Makefile q4wine.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/libQtSql.prl:
/usr/lib/qt4/libQtCore.prl:
/usr/lib/qt4/libQtGui.prl:
/usr/lib/qt4/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile q4wine.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/q4wine1.0.0 || $(MKDIR) .tmp/q4wine1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/q4wine1.0.0/ && $(COPY_FILE) --parents config.h ui_Proccess.h src/initdb.h src/core/registry.h src/core/winebinlauncher.h src/gui/about.h src/gui/appsettings.h src/gui/iconsettings.h src/gui/iconsview.h src/gui/mainwindow.h src/gui/prefixsettings.h src/gui/process.h src/gui/run.h src/gui/wizard.h .tmp/q4wine1.0.0/ && $(COPY_FILE) --parents src/k4wine.qrc .tmp/q4wine1.0.0/ && $(COPY_FILE) --parents src/gui/run.cpp src/main.cpp src/core/registry.cpp src/core/winebinlauncher.cpp src/gui/about.cpp src/gui/appsettings.cpp src/gui/iconsettings.cpp src/gui/iconsview.cpp src/gui/mainwindow.cpp src/gui/prefixsettings.cpp src/gui/process.cpp src/gui/wizard.cpp .tmp/q4wine1.0.0/ && $(COPY_FILE) --parents src/About.ui src/AppSettings.ui src/IconSettings.ui src/IconsView.ui src/MainWindow.ui src/PrefixSettings.ui src/Process.ui src/Run.ui src/Wizard.ui .tmp/q4wine1.0.0/ && $(COPY_FILE) --parents src/i18n/en_us.ts src/i18n/ru_ru.ts src/i18n/uk_ua.ts .tmp/q4wine1.0.0/ && (cd `dirname .tmp/q4wine1.0.0` && $(TAR) q4wine1.0.0.tar q4wine1.0.0 && $(COMPRESS) q4wine1.0.0.tar) && $(MOVE) `dirname .tmp/q4wine1.0.0`/q4wine1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/q4wine1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


/usr/bin/moc:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_winebinlauncher.cpp moc_about.cpp moc_appsettings.cpp moc_iconsettings.cpp moc_iconsview.cpp moc_mainwindow.cpp moc_prefixsettings.cpp moc_process.cpp moc_run.cpp moc_wizard.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_winebinlauncher.cpp moc_about.cpp moc_appsettings.cpp moc_iconsettings.cpp moc_iconsview.cpp moc_mainwindow.cpp moc_prefixsettings.cpp moc_process.cpp moc_run.cpp moc_wizard.cpp
moc_winebinlauncher.cpp: config.h \
		ui_Process.h \
		src/core/winebinlauncher.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) $(INCPATH) src/core/winebinlauncher.h -o moc_winebinlauncher.cpp

moc_about.cpp: config.h \
		ui_About.h \
		src/gui/about.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) $(INCPATH) src/gui/about.h -o moc_about.cpp

moc_appsettings.cpp: ui_AppSettings.h \
		config.h \
		src/gui/appsettings.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) $(INCPATH) src/gui/appsettings.h -o moc_appsettings.cpp

moc_iconsettings.cpp: ui_IconSettings.h \
		config.h \
		src/gui/iconsview.h \
		ui_IconsView.h \
		src/gui/process.h \
		ui_Process.h \
		src/gui/iconsettings.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) $(INCPATH) src/gui/iconsettings.h -o moc_iconsettings.cpp

moc_iconsview.cpp: ui_IconsView.h \
		src/gui/iconsview.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) $(INCPATH) src/gui/iconsview.h -o moc_iconsview.cpp

moc_mainwindow.cpp: ui_MainWindow.h \
		config.h \
		src/gui/iconsview.h \
		ui_IconsView.h \
		src/gui/wizard.h \
		ui_Wizard.h \
		src/core/registry.h \
		src/core/winebinlauncher.h \
		ui_Process.h \
		src/gui/process.h \
		src/gui/iconsettings.h \
		ui_IconSettings.h \
		src/gui/prefixsettings.h \
		ui_PrefixSettings.h \
		src/gui/about.h \
		ui_About.h \
		src/gui/appsettings.h \
		ui_AppSettings.h \
		src/gui/run.h \
		ui_Run.h \
		src/gui/mainwindow.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) $(INCPATH) src/gui/mainwindow.h -o moc_mainwindow.cpp

moc_prefixsettings.cpp: ui_PrefixSettings.h \
		config.h \
		src/gui/prefixsettings.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) $(INCPATH) src/gui/prefixsettings.h -o moc_prefixsettings.cpp

moc_process.cpp: ui_Process.h \
		src/gui/process.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) $(INCPATH) src/gui/process.h -o moc_process.cpp

moc_run.cpp: ui_Run.h \
		config.h \
		src/gui/process.h \
		ui_Process.h \
		src/gui/run.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) $(INCPATH) src/gui/run.h -o moc_run.cpp

moc_wizard.cpp: ui_Wizard.h \
		config.h \
		src/core/registry.h \
		src/core/winebinlauncher.h \
		ui_Process.h \
		src/gui/process.h \
		src/gui/wizard.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) $(INCPATH) src/gui/wizard.h -o moc_wizard.cpp

compiler_rcc_make_all: qrc_k4wine.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_k4wine.cpp
qrc_k4wine.cpp: src/k4wine.qrc \
		src/data/winecfg.png \
		src/data/wine.png \
		src/data/wizard.png \
		src/data/down.png \
		src/data/stop.png \
		src/data/firstc.png \
		src/data/exec.png \
		src/data/exec_wine.png \
		src/data/folder.png \
		src/data/reload.png \
		src/data/up.png \
		src/data/prefixc.png \
		src/data/regedit.png \
		src/data/kill.png \
		src/data/fileopen.png \
		src/data/wineconsole.png \
		src/data/rebuild.png \
		src/data/configure.png \
		src/data/uninstaller.png \
		src/data/notepad.png \
		src/data/explorer.png \
		src/data/info.png \
		src/data/eject.png \
		src/data/folder_open.png
	/usr/bin/rcc -name k4wine src/k4wine.qrc -o qrc_k4wine.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_About.h ui_AppSettings.h ui_IconSettings.h ui_IconsView.h ui_MainWindow.h ui_PrefixSettings.h ui_Process.h ui_Run.h ui_Wizard.h
compiler_uic_clean:
	-$(DEL_FILE) ui_About.h ui_AppSettings.h ui_IconSettings.h ui_IconsView.h ui_MainWindow.h ui_PrefixSettings.h ui_Process.h ui_Run.h ui_Wizard.h
ui_About.h: src/About.ui
	/usr/bin/uic src/About.ui -o ui_About.h

ui_AppSettings.h: src/AppSettings.ui
	/usr/bin/uic src/AppSettings.ui -o ui_AppSettings.h

ui_IconSettings.h: src/IconSettings.ui
	/usr/bin/uic src/IconSettings.ui -o ui_IconSettings.h

ui_IconsView.h: src/IconsView.ui
	/usr/bin/uic src/IconsView.ui -o ui_IconsView.h

ui_MainWindow.h: src/MainWindow.ui
	/usr/bin/uic src/MainWindow.ui -o ui_MainWindow.h

ui_PrefixSettings.h: src/PrefixSettings.ui
	/usr/bin/uic src/PrefixSettings.ui -o ui_PrefixSettings.h

ui_Process.h: src/Process.ui
	/usr/bin/uic src/Process.ui -o ui_Process.h

ui_Run.h: src/Run.ui
	/usr/bin/uic src/Run.ui -o ui_Run.h

ui_Wizard.h: src/Wizard.ui
	/usr/bin/uic src/Wizard.ui -o ui_Wizard.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

run.o: src/gui/run.cpp src/gui/run.h \
		ui_Run.h \
		config.h \
		src/gui/process.h \
		ui_Process.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o run.o src/gui/run.cpp

main.o: src/main.cpp src/gui/mainwindow.h \
		ui_MainWindow.h \
		config.h \
		src/gui/iconsview.h \
		ui_IconsView.h \
		src/gui/wizard.h \
		ui_Wizard.h \
		src/core/registry.h \
		src/core/winebinlauncher.h \
		ui_Process.h \
		src/gui/process.h \
		src/gui/iconsettings.h \
		ui_IconSettings.h \
		src/gui/prefixsettings.h \
		ui_PrefixSettings.h \
		src/gui/about.h \
		ui_About.h \
		src/gui/appsettings.h \
		ui_AppSettings.h \
		src/gui/run.h \
		ui_Run.h \
		src/initdb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

registry.o: src/core/registry.cpp src/core/registry.h \
		config.h \
		src/core/winebinlauncher.h \
		ui_Process.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registry.o src/core/registry.cpp

winebinlauncher.o: src/core/winebinlauncher.cpp src/core/winebinlauncher.h \
		config.h \
		ui_Process.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o winebinlauncher.o src/core/winebinlauncher.cpp

about.o: src/gui/about.cpp src/gui/about.h \
		config.h \
		ui_About.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o src/gui/about.cpp

appsettings.o: src/gui/appsettings.cpp src/gui/appsettings.h \
		ui_AppSettings.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o appsettings.o src/gui/appsettings.cpp

iconsettings.o: src/gui/iconsettings.cpp src/gui/iconsettings.h \
		ui_IconSettings.h \
		config.h \
		src/gui/iconsview.h \
		ui_IconsView.h \
		src/gui/process.h \
		ui_Process.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iconsettings.o src/gui/iconsettings.cpp

iconsview.o: src/gui/iconsview.cpp config.h \
		src/gui/iconsview.h \
		ui_IconsView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iconsview.o src/gui/iconsview.cpp

mainwindow.o: src/gui/mainwindow.cpp src/gui/mainwindow.h \
		ui_MainWindow.h \
		config.h \
		src/gui/iconsview.h \
		ui_IconsView.h \
		src/gui/wizard.h \
		ui_Wizard.h \
		src/core/registry.h \
		src/core/winebinlauncher.h \
		ui_Process.h \
		src/gui/process.h \
		src/gui/iconsettings.h \
		ui_IconSettings.h \
		src/gui/prefixsettings.h \
		ui_PrefixSettings.h \
		src/gui/about.h \
		ui_About.h \
		src/gui/appsettings.h \
		ui_AppSettings.h \
		src/gui/run.h \
		ui_Run.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/gui/mainwindow.cpp

prefixsettings.o: src/gui/prefixsettings.cpp src/gui/prefixsettings.h \
		ui_PrefixSettings.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prefixsettings.o src/gui/prefixsettings.cpp

process.o: src/gui/process.cpp src/gui/process.h \
		ui_Process.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o process.o src/gui/process.cpp

wizard.o: src/gui/wizard.cpp src/gui/wizard.h \
		ui_Wizard.h \
		config.h \
		src/core/registry.h \
		src/core/winebinlauncher.h \
		ui_Process.h \
		src/gui/process.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wizard.o src/gui/wizard.cpp

moc_winebinlauncher.o: moc_winebinlauncher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_winebinlauncher.o moc_winebinlauncher.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

moc_appsettings.o: moc_appsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_appsettings.o moc_appsettings.cpp

moc_iconsettings.o: moc_iconsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iconsettings.o moc_iconsettings.cpp

moc_iconsview.o: moc_iconsview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iconsview.o moc_iconsview.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_prefixsettings.o: moc_prefixsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_prefixsettings.o moc_prefixsettings.cpp

moc_process.o: moc_process.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_process.o moc_process.cpp

moc_run.o: moc_run.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_run.o moc_run.cpp

moc_wizard.o: moc_wizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wizard.o moc_wizard.cpp

qrc_k4wine.o: qrc_k4wine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_k4wine.o qrc_k4wine.cpp

####### Install

install_i18n: all FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/q4wine/i18n/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/q4wine/i18n/ 
	-$(INSTALL_FILE) /home/brezerk/develop/q4wine/src/i18n/en_us.qm $(INSTALL_ROOT)/usr/share/q4wine/i18n/
	-$(INSTALL_FILE) /home/brezerk/develop/q4wine/src/i18n/ru_ru.qm $(INSTALL_ROOT)/usr/share/q4wine/i18n/
	-$(INSTALL_FILE) /home/brezerk/develop/q4wine/src/i18n/uk_ua.qm $(INSTALL_ROOT)/usr/share/q4wine/i18n/


uninstall_i18n:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/q4wine/i18n/en_us.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/q4wine/i18n/ru_ru.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/q4wine/i18n/uk_ua.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/q4wine/i18n/ 


install_theme: all FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/q4wine/themes/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/q4wine/themes/ 
	-$(INSTALL_DIR) /home/brezerk/develop/q4wine/src/theme/nuvola $(INSTALL_ROOT)/usr/share/q4wine/themes/


uninstall_theme:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/q4wine/themes/nuvola
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/q4wine/themes/ 


install_target: all FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install:  install_i18n install_theme install_target  FORCE

uninstall: uninstall_i18n uninstall_theme uninstall_target   FORCE

FORCE:

