.TH "corelib" 3 "8 Jul 2009" "Version 0.113" "q4wine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
corelib \- This class provide general core functions for q4wine.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <src/q4wine-lib/main.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcorelib\fP (bool \fB_GUI_MODE\fP)"
.br
.RI "\fICreate an mainlib class. \fP"
.ti -1c
.RI "QList< QStringList > \fBgetWineProcessList\fP ()"
.br
.RI "\fIThis function tries to get wine process list running in the current system. \fP"
.ti -1c
.RI "QVariant \fBgetSetting\fP (const QString group, const QString key, const bool checkExist=true, const QVariant defaultVal=QVariant()) const "
.br
.RI "\fIThis function get application settings. \fP"
.ti -1c
.RI "QString \fBgetWhichOut\fP (const QString fileName) const "
.br
.RI "\fIThis function get cdrom devices from /etc/fstab file. \fP"
.ti -1c
.RI "QStringList \fBgetCdromDevices\fP (void) const "
.br
.RI "\fIThis function get cdrom devices from /etc/fstab file. \fP"
.ti -1c
.RI "QString \fBgetMountedImages\fP (const QString cdrom_mount) const "
.br
.RI "\fIThis function gets mouted image or media. \fP"
.ti -1c
.RI "bool \fBmountImage\fP (QString image_name, const QString prefix_name) const "
.br
.RI "\fIThis function mount an image or drive to prefix mount point. \fP"
.ti -1c
.RI "bool \fBumountImage\fP (const QString prefix_name) const "
.br
.RI "\fIThis function umount an image or drive from prefix mount point. \fP"
.ti -1c
.RI "bool \fBkillWineServer\fP (const QString prefix_path) const "
.br
.RI "\fIThis function kills wineserver. \fP"
.ti -1c
.RI "bool \fBopenIconDirectry\fP (const QString prefix_name, const QString dir_name, const QString icon_name) const "
.br
.RI "\fIOpen icon folder. \fP"
.ti -1c
.RI "bool \fBrunIcon\fP (const QString prefix_name, const QString dir_name, const QString icon_name) const "
.br
.RI "\fIPrepare icon data for run wine. \fP"
.ti -1c
.RI "bool \fBrunWineBinary\fP (const \fBExecObject\fP execObj) const "
.br
.RI "\fIPrepare icon data for run wine. \fP"
.ti -1c
.RI "bool \fBrunWineBinary\fP (const QString winebinary, const QString cmdargs, const QString prefix_name) const "
.br
.ti -1c
.RI "QString \fBcreateDesktopFile\fP (const QString prefix_name, const QString dir_name, const QString icon_name) const "
.br
.ti -1c
.RI "QString \fBgetWinePath\fP (const QString path, const QString option) const "
.br
.ti -1c
.RI "bool \fBopenPrefixDirectry\fP (const QString prefix_name) const "
.br
.RI "\fIOpen prefix folder. \fP"
.ti -1c
.RI "QStringList \fBgetWineDlls\fP (QString prefix_lib_path) const "
.br
.RI "\fIThis function builds wine dlls list for prefix_lib_path. \fP"
.ti -1c
.RI "bool \fBrunProcess\fP (const QString exec, const QStringList args, QString dir='', bool showLog=TRUE) const "
.br
.RI "\fIRuns process. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "int \fBshowError\fP (const QString message, const bool info) const "
.br
.RI "\fIDisplays error message depending on _GUI_MODE variable value. \fP"
.ti -1c
.RI "void \fBshowError\fP (const QString message) const "
.br
.RI "\fIDisplays error message depending on _GUI_MODE variable value. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fB_GUI_MODE\fP"
.br
.RI "\fIDefine is library operate in CLI or GUI mode. \fP"
.ti -1c
.RI "\fBPrefix\fP * \fBdb_prefix\fP"
.br
.ti -1c
.RI "\fBImage\fP * \fBdb_image\fP"
.br
.ti -1c
.RI "\fBIcon\fP * \fBdb_icon\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class provide general core functions for q4wine. 

It is not useful by itself, but helps to create user-side applications which can use q4wine core functions; 
.PP
Definition at line 114 of file main.h.
.SH "Member Function Documentation"
.PP 
.SS "QStringList corelib::getCdromDevices (void) const"
.PP
This function get cdrom devices from /etc/fstab file. 
.PP
\fBReturns:\fP
.RS 4
Return an list of cdrom devices. 
.RE
.PP

.PP
Definition at line 241 of file main.cpp.
.SS "QString corelib::getMountedImages (const QString cdrom_mount) const"
.PP
This function gets mouted image or media. 
.PP
\fBParameters:\fP
.RS 4
\fIcrom_mount\fP Mount point path. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return an list of cdrom devices. 
.RE
.PP

.PP
Definition at line 319 of file main.cpp.
.SS "QVariant corelib::getSetting (const QString group, const QString key, const bool checkExist = \fCtrue\fP, const QVariant defaultVal = \fCQVariant()\fP) const"
.PP
This function get application settings. 
.PP
\fBParameters:\fP
.RS 4
\fIgroup\fP Settings group. 
.br
\fIkey\fP Settings key. 
.br
\fIdefaultVal\fP Default returned value. 
.br
\fIcheckExist\fP If true - then we need to check exists file or dir by value or not. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return an a key value. 
.RE
.PP

.PP
Definition at line 226 of file main.cpp.
.SS "QString corelib::getWhichOut (const QString fileName) const"
.PP
This function get cdrom devices from /etc/fstab file. 
.PP
\fBReturns:\fP
.RS 4
Return an list of cdrom devices.
.RE
.PP
This function get output from which shell built-in command.
.PP
\fBReturns:\fP
.RS 4
Return the full path of binary. 
.RE
.PP

.PP
Definition at line 290 of file main.cpp.
.SS "QStringList corelib::getWineDlls (QString prefix_lib_path) const"
.PP
This function builds wine dlls list for prefix_lib_path. 
.PP
\fBParameters:\fP
.RS 4
\fIprefix_lib_path\fP Path for wine libs. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return an list of cdrom devices. 
.RE
.PP

.PP
Definition at line 268 of file main.cpp.
.SS "QList< QStringList > corelib::getWineProcessList ()"
.PP
This function tries to get wine process list running in the current system. 
.PP
It gets process values: pid, name, nice priority and WINEPREFIX environment variable 
.PP
\fBNote:\fP
.RS 4
On Linux it uses /proc file system, and on FreeBSD/MacOS it uses /dev/kmem and kvm.h functions. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return an array of QList which contains an QStringList 
.RE
.PP

.PP
Definition at line 47 of file main.cpp.
.SS "bool corelib::killWineServer (const QString prefix_path) const"
.PP
This function kills wineserver. 
.PP
\fBParameters:\fP
.RS 4
\fIprefix_path\fP \fBPrefix\fP name. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return an list of cdrom devices. 
.RE
.PP

.PP
Definition at line 854 of file main.cpp.
.SS "bool corelib::mountImage (QString image_name, const QString prefix_name) const"
.PP
This function mount an image or drive to prefix mount point. 
.PP
\fBParameters:\fP
.RS 4
\fIimage_name\fP \fBImage\fP or drive name. 
.br
\fIprefix_name\fP \fBPrefix\fP name. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return an list of cdrom devices. 
.RE
.PP

.PP
Definition at line 608 of file main.cpp.
.SS "bool corelib::openIconDirectry (const QString prefix_name, const QString dir_name, const QString icon_name) const"
.PP
Open icon folder. 
.PP
\fBParameters:\fP
.RS 4
\fIprefix_name\fP \fBPrefix\fP name. 
.br
\fIdir_name\fP \fBDir\fP name. 
.br
\fIicon_name\fP \fBIcon\fP name. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return true on success. 
.RE
.PP

.PP
Definition at line 753 of file main.cpp.
.SS "bool corelib::openPrefixDirectry (const QString prefix_name) const"
.PP
Open prefix folder. 
.PP
\fBParameters:\fP
.RS 4
\fIprefix_name\fP \fBPrefix\fP name. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return true on success. 
.RE
.PP

.PP
Definition at line 760 of file main.cpp.
.SS "bool corelib::runIcon (const QString prefix_name, const QString dir_name, const QString icon_name) const"
.PP
Prepare icon data for run wine. 
.PP
\fBParameters:\fP
.RS 4
\fIprefix_name\fP \fBPrefix\fP name. 
.br
\fIdir_name\fP \fBDir\fP name. 
.br
\fIicon_name\fP \fBIcon\fP name. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return true on success. 
.RE
.PP

.PP
Definition at line 378 of file main.cpp.
.SS "bool corelib::runProcess (const QString exec, const QStringList args, QString dir = \fC''\fP, bool showLog = \fCTRUE\fP) const"
.PP
Runs process. 
.PP
\fBParameters:\fP
.RS 4
\fIexec\fP Executable path. 
.br
\fIargs\fP Arguments. 
.br
\fIdir\fP Exec directory. 
.RE
.PP
\fBReturns:\fP
.RS 4
True on success. 
.RE
.PP

.PP
Definition at line 787 of file main.cpp.
.SS "bool corelib::runWineBinary (const \fBExecObject\fP execObj) const"
.PP
Prepare icon data for run wine. 
.PP
\fBParameters:\fP
.RS 4
\fI\fBExecObject\fP\fP An icon data struct. 
.br
\fIprefix_name\fP \fBPrefix\fP name. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return true on success. 
.RE
.PP

.PP
Definition at line 396 of file main.cpp.
.SS "void corelib::showError (const QString message) const\fC [private]\fP"
.PP
Displays error message depending on _GUI_MODE variable value. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP Error message. 
.RE
.PP

.PP
Definition at line 841 of file main.cpp.
.SS "int corelib::showError (const QString message, const bool info) const\fC [private]\fP"
.PP
Displays error message depending on _GUI_MODE variable value. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP Error message. 
.br
\fIinfo\fP Define display type. If false - user interactive message. 
.RE
.PP
\fBReturns:\fP
.RS 4
When using an interactive display type, this functions returns a user selected value. 
.RE
.PP

.PP
Definition at line 821 of file main.cpp.
.SS "bool corelib::umountImage (const QString prefix_name) const"
.PP
This function umount an image or drive from prefix mount point. 
.PP
\fBParameters:\fP
.RS 4
\fIprefix_name\fP \fBPrefix\fP name. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return an list of cdrom devices. 
.RE
.PP

.PP
Definition at line 680 of file main.cpp.
.SH "Member Data Documentation"
.PP 
.SS "bool \fBcorelib::_GUI_MODE\fP\fC [private]\fP"
.PP
Define is library operate in CLI or GUI mode. 
.PP
\fBNote:\fP
.RS 4
This is typically need for error message display. 
.RE
.PP

.PP
Definition at line 241 of file main.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for q4wine from the source code.
