.TH "Q4Wine database core" 3 "8 Jul 2009" "Version 0.113" "q4wine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Q4Wine database core \- Database core pakage provide general database functions for q4wine.  

.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataBase\fP"
.br
.RI "\fIThis class provide general database functions for q4wine. \fP"
.ti -1c
.RI "class \fBDir\fP"
.br
.RI "\fIThis class provide database functions for \fBDir\fP table. \fP"
.ti -1c
.RI "class \fBIcon\fP"
.br
.RI "\fIThis class provide database functions for \fBIcon\fP table. \fP"
.ti -1c
.RI "class \fBImage\fP"
.br
.RI "\fIThis class provide database functions for \fBImage\fP table. \fP"
.ti -1c
.RI "class \fBPrefix\fP"
.br
.RI "\fIThis class provide database functions for prefix table. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Database core pakage provide general database functions for q4wine. 
.SH "Author"
.PP 
Generated automatically by Doxygen for q4wine from the source code.
