.TH "DataBase" 3 "15 Jun 2009" "Version 0.113" "q4wine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataBase \- This class provide general database functions for q4wine.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <src/core/database/db.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataBase\fP ()"
.br
.RI "\fIConstructor. \fP"
.ti -1c
.RI "bool \fBcheckDb\fP (const QStringList tables) const "
.br
.RI "\fIThis function tries to check database structure. \fP"
.ti -1c
.RI "void \fBclose\fP ()"
.br
.RI "\fIThis function close database connection. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class provide general database functions for q4wine. 

It is not useful by itself, but it creates database connections and provides basic database check. 
.PP
Definition at line 60 of file db.h.
.SH "Member Function Documentation"
.PP 
.SS "bool DataBase::checkDb (const QStringList tables) const"
.PP
This function tries to check database structure. 
.PP
It gets process values: pid, name, nice priority and WINEPREFIX environment variable. 
.PP
\fBParameters:\fP
.RS 4
\fItables\fP List of tables name. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return true on success otherwise false. 
.RE
.PP

.PP
Definition at line 37 of file db.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for q4wine from the source code.
