.TH "ExecObject" 3 "8 Jul 2009" "Version 0.113" "q4wine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExecObject \- Exec obj struct.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <src/q4wine-lib/main.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBexeccmd\fP"
.br
.ti -1c
.RI "QString \fBprefixid\fP"
.br
.ti -1c
.RI "QString \fBruncmd\fP"
.br
.ti -1c
.RI "QString \fBuseconsole\fP"
.br
.ti -1c
.RI "QString \fBcmdargs\fP"
.br
.ti -1c
.RI "QString \fBoverride\fP"
.br
.ti -1c
.RI "QString \fBwinedebug\fP"
.br
.ti -1c
.RI "QString \fBdisplay\fP"
.br
.ti -1c
.RI "QString \fBwrkdir\fP"
.br
.ti -1c
.RI "QString \fBdesktop\fP"
.br
.ti -1c
.RI "QString \fBnice\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exec obj struct. 
.PP
Definition at line 100 of file main.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for q4wine from the source code.
