.TH "libq4wine-core" 3 "28 May 2009" "Version 0.113" "q4wine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libq4wine-core \- libq4wine-core pakage provide general functions for q4wine-gui and q4wine-cli pakages.  

.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcorelib\fP"
.br
.RI "\fIThis class provide general core functions for q4wine. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcorelib\fP * \fBcreateCoreLib\fP (bool _GUI_MODE)"
.br
.RI "\fIThis function returns a class of \fBcorelib\fP type. \fP"
.in -1c
.SH "Detailed Description"
.PP 
libq4wine-core pakage provide general functions for q4wine-gui and q4wine-cli pakages. 
.SH "Function Documentation"
.PP 
.SS "\fBcorelib\fP* createCoreLib (bool _GUI_MODE)"
.PP
This function returns a class of \fBcorelib\fP type. 
.PP
Here we create an instance of \fBcorelib\fP class and returns its pointer. 
.PP
\fBReturns:\fP
.RS 4
Return an a pointer to core lib class instance. 
.RE
.PP
\fBNote:\fP
.RS 4
This function is exported from shared library. 
.RE
.PP

.PP
Definition at line 39 of file main.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for q4wine from the source code.
