.TH "libq4wine-core" 3 "25 May 2009" "Version 0.113" "q4wine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libq4wine-core \- libq4wine-core provide general functions for q4wine-gui and q4wine-cli pakages  

.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmainlib\fP"
.br
.RI "\fIProvide general functions for q4wine-gui and q4wine-cli pakages. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Q4WINE_EXPORT QString \fBtest\fP ()"
.br
.RI "\fIThis function is exported from shared libarary. So you can use it from other software. \fP"
.in -1c
.SH "Detailed Description"
.PP 
libq4wine-core provide general functions for q4wine-gui and q4wine-cli pakages 
.SH "Function Documentation"
.PP 
.SS "Q4WINE_EXPORT QString test ()"
.PP
This function is exported from shared libarary. So you can use it from other software. 
.PP
\fBReturns:\fP
.RS 4
Return some QString text value
.RE
.PP
This function is exported from shared libarary 
.PP
Create \fBmainlib\fP class copy
.PP
Here ve call for \fBmainlib.getHello()\fP function to take hello text 
.SH "Author"
.PP 
Generated automatically by Doxygen for q4wine from the source code.
