.TH "mainlib" 3 "26 May 2009" "Version 0.113" "q4wine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainlib \- Provide general functions for q4wine-gui and q4wine-cli pakages.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <src/q4wine-lib/main.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmainlib\fP ()"
.br
.RI "\fICreate an \fBmainlib\fP class. \fP"
.ti -1c
.RI "QString \fBgetHello\fP ()"
.br
.RI "\fIThis is just a test method. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Provide general functions for q4wine-gui and q4wine-cli pakages. 

This class provide core functions for q4wine. It is not useful by itself, but helps to create user-side applications which can use q4wine core functions;
.PP
\fBNote:\fP
.RS 4
This is still in development state ;) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "QString mainlib::getHello ()"
.PP
This is just a test method. 
.PP
\fBReturns:\fP
.RS 4
Return some QString text value
.RE
.PP
This method does NOT do useful things. And returns exceptionally useful results. Use it everyday with good health. 

.SH "Author"
.PP 
Generated automatically by Doxygen for q4wine from the source code.
