.TH "Prefix" 3 "8 Jul 2009" "Version 0.113" "q4wine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Prefix \- This class provide database functions for prefix table.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <src/core/database/prefix.h>\fP
.PP
Inherited by \fBDir\fP, \fBIcon\fP, and \fBImage\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPrefix\fP ()"
.br
.RI "\fIThis is calss constructor. \fP"
.ti -1c
.RI "QList< QStringList > \fBgetFields\fP (const QStringList fields) const "
.br
.RI "\fIThis function gets requested table fields from table. \fP"
.ti -1c
.RI "QList< QStringList > \fBgetFieldsByKey\fP (const QStringList fields, const QStringList keys, const QStringList vals) const "
.br
.RI "\fIThis function get requested table fields by keys value from table. \fP"
.ti -1c
.RI "QList< QStringList > \fBgetFieldsByKey\fP (const QString key, const QString val) const "
.br
.RI "\fIThis function gets all table fields by key value from table. \fP"
.ti -1c
.RI "QList< QStringList > \fBgetFields\fP (void) const "
.br
.RI "\fIThis function get all fields from prefix table. \fP"
.ti -1c
.RI "QStringList \fBgetFieldsByPrefixName\fP (const QString prefix_name) const "
.br
.RI "\fIThis function gets all table fields by prefixName key value from table. \fP"
.ti -1c
.RI "QStringList \fBgetFieldsByPrefixId\fP (const QString prefix_id) const "
.br
.RI "\fIThis function gets all table fields by prefix id key value from table. \fP"
.ti -1c
.RI "QString \fBgetId\fP (const QString prefix_name) const "
.br
.RI "\fIThis function gets prefix id by name. \fP"
.ti -1c
.RI "QString \fBgetPath\fP (const QString prefix_name) const "
.br
.RI "\fIThis function gets prefix path by name. \fP"
.ti -1c
.RI "QString \fBgetMountPath\fP (const QString prefix_name) const "
.br
.RI "\fIThis function gets prefix cdrom mount path by name. \fP"
.ti -1c
.RI "bool \fBdelByName\fP (const QString prefix_name) const "
.br
.RI "\fIThis function deletes all prefix fields by prefix_name keys value from table. \fP"
.ti -1c
.RI "bool \fBaddPrefix\fP (const QString prefix_name, const QString prefix_path='', const QString wine_exec='', const QString wine_server='', const QString wine_loader='', const QString wine_dllpath='', const QString cdrom_mount='', const QString cdrom_drive='') const "
.br
.RI "\fIThis function deletes all prefix fields by prefix_name keys value from table. \fP"
.ti -1c
.RI "bool \fBupdatePrefix\fP (const QString prefix_name, const QString prefix_path, const QString wine_exec, const QString wine_server, const QString wine_loader, const QString wine_dllpath, const QString cdrom_mount, const QString cdrom_drive, const QString old_prefix_name) const "
.br
.RI "\fIThis function deletes all prefix fields by prefix_name keys value from table. \fP"
.ti -1c
.RI "bool \fBupdateQuery\fP (QSqlQuery *sqlQuery) const "
.br
.RI "\fIThis function executes requested query. \fP"
.ti -1c
.RI "bool \fBisExistsByName\fP (const QString prefix_name) const "
.br
.RI "\fIThis function check is reccord exists by prefix name or not. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QString \fB_TABLE\fP"
.br
.RI "\fIThis variable defines which table is used by class. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class provide database functions for prefix table. 
.PP
Definition at line 51 of file prefix.h.
.SH "Member Function Documentation"
.PP 
.SS "bool Prefix::addPrefix (const QString prefix_name, const QString prefix_path = \fC''\fP, const QString wine_exec = \fC''\fP, const QString wine_server = \fC''\fP, const QString wine_loader = \fC''\fP, const QString wine_dllpath = \fC''\fP, const QString cdrom_mount = \fC''\fP, const QString cdrom_drive = \fC''\fP) const"
.PP
This function deletes all prefix fields by prefix_name keys value from table. 
.PP
\fBParameters:\fP
.RS 4
\fIprefix_name\fP A prefix name value. 
.br
\fIprefix_path\fP A prefix path value. 
.br
\fIwine_exec\fP A wine executable binary. 
.br
\fIwine_server\fP A wine server binary. 
.br
\fIwine_loader\fP A wine loader binary. 
.br
\fIwine_dllpath\fP A wine library directory. 
.br
\fIcdrom_mount\fP A cdrom mount directory. 
.br
\fIcdrom_drive\fP A cdrom drive. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return true on success. 
.RE
.PP

.PP
Definition at line 261 of file prefix.cpp.
.SS "bool Prefix::delByName (const QString prefix_name) const"
.PP
This function deletes all prefix fields by prefix_name keys value from table. 
.PP
\fBParameters:\fP
.RS 4
\fIprefix_name\fP A prefix name value. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return true on success. 
.RE
.PP

.PP
Definition at line 248 of file prefix.cpp.
.SS "QList< QStringList > Prefix::getFields (void) const"
.PP
This function get all fields from prefix table. 
.PP
\fBReturns:\fP
.RS 4
Return a list of table fields value or -1 on error. 
.RE
.PP

.PP
Reimplemented in \fBImage\fP.
.PP
Definition at line 66 of file prefix.cpp.
.SS "QList< QStringList > Prefix::getFields (const QStringList fields) const"
.PP
This function gets requested table fields from table. 
.PP
\fBParameters:\fP
.RS 4
\fIfields\fP List of table fields names. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return QList of QStringList with selected value or -1 on error. 
.RE
.PP

.PP
Definition at line 37 of file prefix.cpp.
.SS "QList<QStringList> Prefix::getFieldsByKey (const QString key, const QString val) const"
.PP
This function gets all table fields by key value from table. 
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP A table key field name. 
.br
\fIval\fP A table key field value. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return a list of table fields value or -1 on error. 
.RE
.PP

.SS "QList< QStringList > Prefix::getFieldsByKey (const QStringList fields, const QStringList keys, const QStringList vals) const"
.PP
This function get requested table fields by keys value from table. 
.PP
\fBParameters:\fP
.RS 4
\fIfields\fP A table fields names. 
.br
\fIkeys\fP A table key fields names. 
.br
\fIvals\fP A table key fields values. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return a list of table fields value or -1 on error. 
.RE
.PP

.PP
Definition at line 87 of file prefix.cpp.
.SS "QStringList Prefix::getFieldsByPrefixId (const QString prefix_id) const"
.PP
This function gets all table fields by prefix id key value from table. 
.PP
\fBParameters:\fP
.RS 4
\fIprefix_id\fP \fBPrefix\fP id key value. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return a list of table fields value or -1 on error. 
.RE
.PP

.PP
Reimplemented in \fBDir\fP.
.PP
Definition at line 217 of file prefix.cpp.
.SS "QStringList Prefix::getFieldsByPrefixName (const QString prefix_name) const"
.PP
This function gets all table fields by prefixName key value from table. 
.PP
\fBParameters:\fP
.RS 4
\fIprefixName\fP \fBPrefix\fP name key value. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return a list of table fields value or -1 on error. 
.RE
.PP

.PP
Reimplemented in \fBDir\fP.
.PP
Definition at line 126 of file prefix.cpp.
.SS "QString Prefix::getId (const QString prefix_name) const"
.PP
This function gets prefix id by name. 
.PP
\fBParameters:\fP
.RS 4
\fIprefix_name\fP A prefix name value. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return prefix id. 
.RE
.PP

.PP
Definition at line 148 of file prefix.cpp.
.SS "QString Prefix::getMountPath (const QString prefix_name) const"
.PP
This function gets prefix cdrom mount path by name. 
.PP
\fBParameters:\fP
.RS 4
\fIprefix_name\fP A prefix name value. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return prefix path. 
.RE
.PP

.PP
Definition at line 194 of file prefix.cpp.
.SS "QString Prefix::getPath (const QString prefix_name) const"
.PP
This function gets prefix path by name. 
.PP
\fBParameters:\fP
.RS 4
\fIprefix_name\fP A prefix name value. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return prefix path. 
.RE
.PP

.PP
Reimplemented in \fBImage\fP.
.PP
Definition at line 171 of file prefix.cpp.
.SS "bool Prefix::isExistsByName (const QString prefix_name) const"
.PP
This function check is reccord exists by prefix name or not. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP A prefix name value. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return true if exists. 
.RE
.PP

.PP
Reimplemented in \fBImage\fP.
.PP
Definition at line 383 of file prefix.cpp.
.SS "bool Prefix::updatePrefix (const QString prefix_name, const QString prefix_path, const QString wine_exec, const QString wine_server, const QString wine_loader, const QString wine_dllpath, const QString cdrom_mount, const QString cdrom_drive, const QString old_prefix_name) const"
.PP
This function deletes all prefix fields by prefix_name keys value from table. 
.PP
\fBParameters:\fP
.RS 4
\fIprefix_name\fP A prefix name value. 
.br
\fIprefix_path\fP A prefix path value. 
.br
\fIwine_exec\fP A wine executable binary. 
.br
\fIwine_server\fP A wine server binary. 
.br
\fIwine_loader\fP A wine loader binary. 
.br
\fIwine_dllpath\fP A wine library directory. 
.br
\fIcdrom_mount\fP A cdrom mount directory. 
.br
\fIcdrom_drive\fP A cdrom drive. 
.br
\fIold_prefix_name\fP A cdrom drive. 
.RE
.PP
\fBReturns:\fP
.RS 4
Return true on success. 
.RE
.PP

.PP
Definition at line 321 of file prefix.cpp.
.SS "bool Prefix::updateQuery (QSqlQuery * sqlQuery) const"
.PP
This function executes requested query. 
.PP
\fBParameters:\fP
.RS 4
\fISQL\fP Query 
.RE
.PP
\fBReturns:\fP
.RS 4
Return true on success 
.RE
.PP

.PP
Definition at line 240 of file prefix.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for q4wine from the source code.
