.TH "-gui Q4Wine GUI" 3 "8 Jul 2009" "Version 0.113" "q4wine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
-gui Q4Wine GUI \- q4wine-gui pakage provide general GUI functions for q4wine.  

.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIconSettings\fP"
.br
.RI "\fI.IP "\(bu" 2

.PP
\fP"
.ti -1c
.RI "class \fBImageManager\fP"
.br
.RI "\fI.IP "\(bu" 2

.PP
\fP"
.ti -1c
.RI "class \fBPrefixSettings\fP"
.br
.RI "\fI.IP "\(bu" 2

.PP
\fP"
.ti -1c
.RI "class \fBRun\fP"
.br
.RI "\fI.IP "\(bu" 2

.PP
\fP"
.ti -1c
.RI "class \fBWizard\fP"
.br
.RI "\fI.IP "\(bu" 2

.PP
\fP"
.in -1c
.SH "Detailed Description"
.PP 
q4wine-gui pakage provide general GUI functions for q4wine. 
.SH "Author"
.PP 
Generated automatically by Doxygen for q4wine from the source code.
