/***************************************************************************
 *   Copyright (C) 2008-2025 by Oleksii S. Malakhov <brezerk@gmail.com>    *
 *                                                                         *
 *   This program is free software: you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation, either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>. *
 *                                                                         *
 ***************************************************************************/

/*
 * Do NOT edit this file
 *
 * This file will be replaced by cmake and tools/gen_authors.py.
 * Edit src/q4wine-gui/authors.yaml file instead.
 *
 */

#define T_TRANSLATIONS                                                        \
  "<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.0//EN' "                         \
  "'http://www.w3.org/TR/REC-html40/strict.dtd'>"                             \
  "<html>"                                                                    \
  "<head>"                                                                    \
  "<meta name='qrichtext' content='1' />"                                     \
  "<style type='text/css'>p, li { white-space: pre-wrap; }</style>"           \
  "</head>"                                                                   \
  "<body>"                                                                    \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Oleksii S. Malakhov (brezerk)"                                             \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Ukrainian translation"                                                     \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>E-Mail</span>: <a "                           \
  "href='mailto:brezerk@gmail.com' style='text-decoration: none; "            \
  "color:#5f9ea0;'>brezerk@gmail.com</a>"                                     \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>Web</span>: <a "                              \
  "href='https://brezblock.org.ua' "                                          \
  "style='color:#5f9ea0;'>https://brezblock.org.ua</a>"                       \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Kyiv, Ukraine"                                                             \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  " "                                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Danie Wessels (DanieW)"                                                    \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Afrikaans translation"                                                     \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>E-Mail</span>: <a "                           \
  "href='mailto:danie.wessels@live.co.za' style='text-decoration: none; "     \
  "color:#5f9ea0;'>danie.wessels@live.co.za</a>"                              \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>Web</span>: <a "                              \
  "href='https://sites.google.com/site/pcproblemdoctor/' "                    \
  "style='color:#5f9ea0;'>https://sites.google.com/site/pcproblemdoctor/</a>" \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Centurion, Gauteng, South Africa"                                          \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  " "                                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Carlos Ignacio Ruax "                                                      \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Spanish translation"                                                       \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>E-Mail</span>: <a "                           \
  "href='mailto:ignacioruax@gmail.com' style='text-decoration: none; "        \
  "color:#5f9ea0;'>ignacioruax@gmail.com</a>"                                 \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Spain"                                                                     \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  " "                                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Ercole Carpanetto (ercolinux)"                                             \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Italian translation"                                                       \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>E-Mail</span>: <a "                           \
  "href='mailto:ercole69@gmail.com' style='text-decoration: none; "           \
  "color:#5f9ea0;'>ercole69@gmail.com</a>"                                    \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Italy"                                                                     \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  " "                                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Franciszek Janowski (nobange)"                                             \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Polish translation"                                                        \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>E-Mail</span>: <a "                           \
  "href='mailto:nobange@poczta.onet.pl' style='text-decoration: none; "       \
  "color:#5f9ea0;'>nobange@poczta.onet.pl</a>"                                \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Poland"                                                                    \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  " "                                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Jeff Huang (s8321414)"                                                     \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "zh_tw locale translator"                                                   \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>E-Mail</span>: <a "                           \
  "href='mailto:s8321414@gmail.com' style='text-decoration: none; "           \
  "color:#5f9ea0;'>s8321414@gmail.com</a>"                                    \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>Web</span>: <a "                              \
  "href='https://about.me/s8321414' "                                         \
  "style='color:#5f9ea0;'>https://about.me/s8321414</a>"                      \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Taiwan"                                                                    \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  " "                                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Marcio Moraes "                                                            \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Portuguese (Brazil) translation"                                           \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>E-Mail</span>: <a "                           \
  "href='mailto:marciopanto@gmail.com' style='text-decoration: none; "        \
  "color:#5f9ea0;'>marciopanto@gmail.com</a>"                                 \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Italy"                                                                     \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  " "                                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Masanori Kakura (kakurasan)"                                               \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Japanese translation"                                                      \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>E-Mail</span>: <a "                           \
  "href='mailto:kakurasan@gmail.com' style='text-decoration: none; "          \
  "color:#5f9ea0;'>kakurasan@gmail.com</a>"                                   \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>Web</span>: <a "                              \
  "href='https://kakurasan.blogspot.com/' "                                   \
  "style='color:#5f9ea0;'>https://kakurasan.blogspot.com/</a>"                \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Japan"                                                                     \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  " "                                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Mingye Wang "                                                              \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Chinese (China) translation"                                               \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Wilton, CT, USA"                                                           \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  " "                                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Yaron Shahrabani "                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Hebrew translation"                                                        \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>E-Mail</span>: <a "                           \
  "href='mailto:sh.yaron@gmail.com' style='text-decoration: none; "           \
  "color:#5f9ea0;'>sh.yaron@gmail.com</a>"                                    \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>Web</span>: <a "                              \
  "href='https://launchpad.net/~sh-yaron' "                                   \
  "style='color:#5f9ea0;'>https://launchpad.net/~sh-yaron</a>"                \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Misgav, Israel"                                                            \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  " "                                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Pavel Fric "                                                               \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Czech translation"                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>Web</span>: <a "                              \
  "href='http://fripohled.blogspot.com/' "                                    \
  "style='color:#5f9ea0;'>http://fripohled.blogspot.com/</a>"                 \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Czech Republic"                                                            \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  " "                                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Ron Widler "                                                               \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "German translation"                                                        \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  " "                                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Rosva "                                                                    \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Persian Translation"                                                       \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>E-Mail</span>: <a "                           \
  "href='mailto:mojsh2020@gmail.com' style='text-decoration: none; "          \
  "color:#5f9ea0;'>mojsh2020@gmail.com</a>"                                   \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>Web</span>: <a "                              \
  "href='http://20ss20.wordpress.com' "                                       \
  "style='color:#5f9ea0;'>http://20ss20.wordpress.com</a>"                    \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Talesh, Iran"                                                              \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  " "                                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Frederik Schwarzer (icwiener) "                                            \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "German translation"                                                        \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  " "                                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Uriy O. Chornoivan "                                                       \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Ukrainian translation"                                                     \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>E-Mail</span>: <a "                           \
  "href='mailto:yurchor@ukr.net' style='text-decoration: none; "              \
  "color:#5f9ea0;'>yurchor@ukr.net</a>"                                       \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "Kyiv, Ukraine"                                                             \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  " "                                                                         \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "seigneurfuo "                                                              \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "French translation"                                                        \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  "<span style='color:#6495ed;'>Web</span>: <a "                              \
  "href='https://seigneurfuo.wordpress.com' "                                 \
  "style='color:#5f9ea0;'>https://seigneurfuo.wordpress.com</a>"              \
  "</p>"                                                                      \
  "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; "            \
  "margin-right:0px; -qt-block-indent:0; text-indent:0px;'>"                  \
  " "                                                                         \
  "</p>"                                                                      \
  "</body>"                                                                   \
  "<html>"
