/***************************************************************************
*   Copyright (C) 2008-2017 by Oleksii S. Malakhov <brezerk@gmail.com>    *
*                                                                         *
*   This program is free software: you can redistribute it and/or modify  *
*   it under the terms of the GNU General Public License as published by  *
*   the Free Software Foundation, either version 3 of the License, or     *
*   (at your option) any later version.                                   *
*                                                                         *
*   This program is distributed in the hope that it will be useful,       *
*   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
*   GNU General Public License for more details.                          *
*                                                                         *
*   You should have received a copy of the GNU General Public License     *
*   along with this program.  If not, see <http://www.gnu.org/licenses/>. *
*                                                                         *
***************************************************************************/

/*
 * Do NOT edit this file
 *
 * This file will be replaced by cmake and toos/gen_authors.py.
 * Edit src/q4wine-gui/authors.yaml file instead.
 *
 */


#define T_DEVELOPERS "<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.0//EN' 'http://www.w3.org/TR/REC-html40/strict.dtd'>" \
"<html>" \
    "<head>" \
        "<meta name='qrichtext' content='1' />" \
	"<style type='text/css'>p, li { white-space: pre-wrap; }</style>" \
    "</head>" \
    "<body>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Oleksii S. Malakhov (brezerk)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Project maintainer, lead developer, website designer and developer, project documentation, support etc. ;)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:brezerk@gmail.com' style='text-decoration: none; color:#5f9ea0;'>brezerk@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Jabber</span>: <a href='mailto:brezerk@jabber.com.ua' style='text-decoration: none; color:#5f9ea0;'>brezerk@jabber.com.ua</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Web</span>: <a href='http://brezblock.org.ua' style='color:#5f9ea0;'>http://brezblock.org.ua</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Kiev, Ukraine" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Sergey Skrypnic (opium)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Website developer, hosting administration" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:opium@jabber.com.ua' style='text-decoration: none; color:#5f9ea0;'>opium@jabber.com.ua</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Kharkov, Ukraine" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Pavel Zinin (pashazz)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Winetricks support, fixes" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:pzinin@gmail.com' style='text-decoration: none; color:#5f9ea0;'>pzinin@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Sergiev Posad, Moscow region, Russia" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Dmitry Marakasov (amdmi3)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "FreeBSD support fixes" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:amdmi3@amdmi3.ru' style='text-decoration: none; color:#5f9ea0;'>amdmi3@amdmi3.ru</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Moscow, Russia" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Xavier Corredor Llano " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "build-in nuvoX icon theme" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:xavier.corredor.llano@gmail.com' style='text-decoration: none; color:#5f9ea0;'>xavier.corredor.llano@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
     "</body>" \
"<html>"

#define T_TRANSLATIONS "<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.0//EN' 'http://www.w3.org/TR/REC-html40/strict.dtd'>" \
"<html>" \
    "<head>" \
        "<meta name='qrichtext' content='1' />" \
	"<style type='text/css'>p, li { white-space: pre-wrap; }</style>" \
    "</head>" \
    "<body>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Oleksii S. Malakhov (brezerk)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Ukrainian translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:brezerk@gmail.com' style='text-decoration: none; color:#5f9ea0;'>brezerk@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Jabber</span>: <a href='mailto:brezerk@jabber.com.ua' style='text-decoration: none; color:#5f9ea0;'>brezerk@jabber.com.ua</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Web</span>: <a href='http://brezblock.org.ua' style='color:#5f9ea0;'>http://brezblock.org.ua</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Kiev, Ukraine" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Boris Pek (tehnick)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Russian translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:tehnick-8@yandex.ru' style='text-decoration: none; color:#5f9ea0;'>tehnick-8@yandex.ru</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Jabber</span>: <a href='mailto:tehnick-8@jabber.ru' style='text-decoration: none; color:#5f9ea0;'>tehnick-8@jabber.ru</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Web</span>: <a href='https://tehnick.github.io/' style='color:#5f9ea0;'>https://tehnick.github.io/</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Russian Federation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Danie Wessels (DanieW)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Afrikaans translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:danie.wessels@live.co.za' style='text-decoration: none; color:#5f9ea0;'>danie.wessels@live.co.za</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Web</span>: <a href='https://sites.google.com/site/pcproblemdoctor/' style='color:#5f9ea0;'>https://sites.google.com/site/pcproblemdoctor/</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Centurion, Gauteng, South Africa" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Carlos Ignacio Ruax " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Spanish translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:ignacioruax@gmail.com' style='text-decoration: none; color:#5f9ea0;'>ignacioruax@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Spain" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Ercole Carpanetto (ercolinux)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Italian translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:ercole69@gmail.com' style='text-decoration: none; color:#5f9ea0;'>ercole69@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Italy" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Franciszek Janowski (nobange)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Polish translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:nobange@poczta.onet.pl' style='text-decoration: none; color:#5f9ea0;'>nobange@poczta.onet.pl</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Poland" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Jeff Huang (s8321414)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "zh_tw locale translator" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:s8321414@gmail.com' style='text-decoration: none; color:#5f9ea0;'>s8321414@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Web</span>: <a href='https://about.me/s8321414' style='color:#5f9ea0;'>https://about.me/s8321414</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Taiwan" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Marcio Moraes " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Portuguese (Brazil) translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:marciopanto@gmail.com' style='text-decoration: none; color:#5f9ea0;'>marciopanto@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Italy" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Masanori Kakura (kakurasan)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Japanese translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:kakurasan@gmail.com' style='text-decoration: none; color:#5f9ea0;'>kakurasan@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Web</span>: <a href='https://kakurasan.blogspot.com/' style='color:#5f9ea0;'>https://kakurasan.blogspot.com/</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Japan" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Mingye Wang " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Chinese (China) translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Wilton, CT, USA" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Yaron Shahrabani " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Hebrew translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:sh.yaron@gmail.com' style='text-decoration: none; color:#5f9ea0;'>sh.yaron@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Web</span>: <a href='https://launchpad.net/~sh-yaron' style='color:#5f9ea0;'>https://launchpad.net/~sh-yaron</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Misgav, Israel" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Pavel Fric " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Czech translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Web</span>: <a href='http://fripohled.blogspot.com/' style='color:#5f9ea0;'>http://fripohled.blogspot.com/</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Czech Republic" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Pavel Zinin (pashazz)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Russian translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:pzinin@gmail.com' style='text-decoration: none; color:#5f9ea0;'>pzinin@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Sergiev Posad, Moscow region, Russia" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Ron Widler " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "German translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Rosva " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Persian Translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:mojsh2020@gmail.com' style='text-decoration: none; color:#5f9ea0;'>mojsh2020@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Web</span>: <a href='http://20ss20.wordpress.com' style='color:#5f9ea0;'>http://20ss20.wordpress.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Talesh, Iran" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Frederik Schwarzer (icwiener) " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "German translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Uriy O. Chornoivan " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Ukrainian translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:yurchor@ukr.net' style='text-decoration: none; color:#5f9ea0;'>yurchor@ukr.net</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Kiev, Ukraine" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
     "</body>" \
"<html>"

#define T_PKG_MAINTAINERS "<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.0//EN' 'http://www.w3.org/TR/REC-html40/strict.dtd'>" \
"<html>" \
    "<head>" \
        "<meta name='qrichtext' content='1' />" \
	"<style type='text/css'>p, li { white-space: pre-wrap; }</style>" \
    "</head>" \
    "<body>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Boris Pek (tehnick)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Debian and Ubuntu package maintainer, some fixes" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:tehnick-8@yandex.ru' style='text-decoration: none; color:#5f9ea0;'>tehnick-8@yandex.ru</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Jabber</span>: <a href='mailto:tehnick-8@jabber.ru' style='text-decoration: none; color:#5f9ea0;'>tehnick-8@jabber.ru</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Web</span>: <a href='https://tehnick.github.io/' style='color:#5f9ea0;'>https://tehnick.github.io/</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Russian Federation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Dmitrij S. Kryzhevich " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Fedora package maintainer" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Ercole Carpanetto (ercolinux)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "openmamba package maintainer" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:ercole69@gmail.com' style='text-decoration: none; color:#5f9ea0;'>ercole69@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Italy" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Kyrill Detinov (Lazy_Kent)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "openSUSE package maintainer" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:lazy.kent@opensuse.org' style='text-decoration: none; color:#5f9ea0;'>lazy.kent@opensuse.org</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Russia" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Markos Chandras (hwoarang)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Gentoo ebuild maintainer" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:hwoarang@gentoo.org' style='text-decoration: none; color:#5f9ea0;'>hwoarang@gentoo.org</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Web</span>: <a href='http://hwoarang.silverarrow.gr' style='color:#5f9ea0;'>http://hwoarang.silverarrow.gr</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Greece" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Rusmir Dusko " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "FreeBSD port maintainer" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:nemysis@FreeBSD.org' style='text-decoration: none; color:#5f9ea0;'>nemysis@FreeBSD.org</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Sergey V. Dyatko " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "FreeBSD port maintainer" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:sergey.dyatko@gmail.com' style='text-decoration: none; color:#5f9ea0;'>sergey.dyatko@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Minsk, Republic of Belarus" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
     "</body>" \
"<html>"

#define T_THANKS "<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.0//EN' 'http://www.w3.org/TR/REC-html40/strict.dtd'>" \
"<html>" \
    "<head>" \
        "<meta name='qrichtext' content='1' />" \
	"<style type='text/css'>p, li { white-space: pre-wrap; }</style>" \
    "</head>" \
    "<body>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<img src=':emblem-favorite' width='16'/> Irina V. Malakhova " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Thanks for patience, love and countenance =]" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Sergey V. Dyatko " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Suppot, assistance, testing and advice for FreeBSD port" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:sergey.dyatko@gmail.com' style='text-decoration: none; color:#5f9ea0;'>sergey.dyatko@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Sergey Golivets (B@RT)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Testing, bugreports and feature requests" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Jabber</span>: <a href='mailto:bartlab@jabber.ru' style='text-decoration: none; color:#5f9ea0;'>bartlab@jabber.ru</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Ukraine, Mariupol" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Sergey Skrypnic (opium) " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Website developer, hosting administration" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:opium@jabber.com.ua' style='text-decoration: none; color:#5f9ea0;'>opium@jabber.com.ua</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Kharkov, Ukraine" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Boris Pek (tehnick)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Bug reports, testing, some fixes" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:tehnick-8@yandex.ru' style='text-decoration: none; color:#5f9ea0;'>tehnick-8@yandex.ru</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Jabber</span>: <a href='mailto:tehnick-8@jabber.ru' style='text-decoration: none; color:#5f9ea0;'>tehnick-8@jabber.ru</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Web</span>: <a href='https://tehnick.github.io/' style='color:#5f9ea0;'>https://tehnick.github.io/</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Russian Federation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Dmitry Marakasov (amdmi3)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Ukrainian translation" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:amdmi3@amdmi3.ru' style='text-decoration: none; color:#5f9ea0;'>amdmi3@amdmi3.ru</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Russia" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Sergey Kishchenko (tilarids)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Testing, bug reports" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:voidwrk@gmail.com' style='text-decoration: none; color:#5f9ea0;'>voidwrk@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Kharkov, Ukraine" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Kyrill Detinov (Lazy_Kent)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Testing, bug reports" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:lazy.kent@opensuse.org' style='text-decoration: none; color:#5f9ea0;'>lazy.kent@opensuse.org</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Russia" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Andrey A. Maloshtan " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Testing, bug reports" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:andrey.aleksandrovich@googlemail.com' style='text-decoration: none; color:#5f9ea0;'>andrey.aleksandrovich@googlemail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Kharkov, Ukraine" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Masanori Kakura (kakurasan)" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Bug reports, testing, some fixes, feature requests" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>E-Mail</span>: <a href='mailto:kakurasan@gmail.com' style='text-decoration: none; color:#5f9ea0;'>kakurasan@gmail.com</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "<span style='color:#6495ed;'>Web</span>: <a href='https://kakurasan.blogspot.com/' style='color:#5f9ea0;'>https://kakurasan.blogspot.com/</a>" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    "Japan" \
	"</p>" \
        "<p style='margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;'>" \
	    " " \
	"</p>" \
     "</body>" \
"<html>"
