.TH "q4wine" "1" "13 Apr 2025" "Q4Wine 1.4 Manual" "Q4Wine Manual"
.SH "NAME"
q4wine \- runs GUI utility for Wine applications and prefixes management.
.SH "SYNOPSIS"
\fBq4wine\fR [\fBKEY\fR] ...
.SH "DESCRIPTION"
Q4Wine is a Qt
.I https://www.qt.io/
GUI for W.I.N.E.
.I http://winehq.org/
It will help you manage wine prefixes and installed applications.
.SS General features:
.br
- Can export Qt color theme into wine colors settings.
.br
- Can easy work with different wine versions at same time;
.br
- Integrated Wine AppDB browser;
.br
- Easy creating, deleting and managing prefixes (WINEPREFIX);
.br
- Easy controlling for wine process;
.br
- autostart icons support;
.br
- Easy cd-image use;
.br
- FuseISO\\Embedded FuseISO mount profiles;
.br
- You can extract icons from PE files (.exe .dll);
.br
- Easy backup and restore for managed prefixes.
.br
- Winetricks support.
.br
- and more...
.SH "OPTIONS"
.RB "A summary of options is included below."
.TP
.BR "\-m,  \-\-minimize"
minimize Q4Wine main window on startup
.TP
.BR "\-h,  \-\-help"
display help and exit
.TP
.BR "\-v,  \-\-version"
output version information and exit
.TP
.BR "\-b,  \-\-binary"
open run dialog for wine binary to execute wine binary
.SH "EXIT STATUS"
.B 0
if OK or
.B \-1
if serious troubles
.SH "FILES"
.TP
.I /usr/bin/q4wine
The
.B Q4Wine
main gui program
.TP
.I /usr/bin/q4wine-cli
The
.B Q4Wine
command line interface program
.TP
.I /usr/bin/q4wine-helper
The
.B Q4Wine
runner helper program
.TP
.I /usr/lib/q4wine
Directory containing
.B Q4Wine's
shared libraries
.TP
.I $HOME/.config/q4wine
Directory containing Q4Wine config, icons, database and temporary files.

.SH "AUTHORS"
.SS Thanks to all:
Q4Wine is available thanks to the work of many to all people, who was
involved in development process, testing, bugreporting, packaging or
translation creation. For a full listing of the authors, please see
the file
.B AUTHORS
in the top-level directory of the source distribution.

.SS Created by:
.TP
Oleksii S. Malakhov (brezerk) <\fBbrezerk at gmail.com\fR>
Project maintainer, lead developer, web site designer and developer,
project documentation, support, etc. ;)

.SH "COPYRIGHT"
Q4Wine can be distributed under the terms of the GPLv3 license.
A copy of the license is in the file
.B LICENSE
in the top-level directory of the source distribution.

.SH "AVAILABILITY"
The most recent
.B public
version of Wine can be downloaded from
.I https://q4wine.brezblock.org.ua/download/

The latest snapshot of the code may be obtained via
.B GIT
for information on how to do this, please see
.I https://q4wine.brezblock.org.ua/download/#git

Q4Wine, development headquarters, is at
.I https://q4wine.brezblock.org.ua
This website contains a great deal of information about Q4Wine.

.SH "BUGS"
If you find a bug in Q4Wine please report it to
<\fBbrezerk at gmail.com\fR> or directly to Q4Wine
bug tracker
.I https://sourceforge.net/projects/q4wine/
.PP
.SH "SEE ALSO"
.PP
\fBq4wine-cli\fR(1),
\fBq4wine-helper\fR(1),
\fBwine\fR(1),
\fBwineserver\fR(1)\&
