.TH "q4wine-cli" "1" "27 Jan 2016" "Q4Wine 1.2-r2 Manual" "Q4Wine Manual"
.SH "NAME"
q4wine-cli \- console utility for wine applications and prefixes management.
.SH SYNOPSIS
\fBq4wine-cli\fR [\fBKEY\fR] ...
.br
.B q4wine-cli
\-p <prefix_name> [\-d <dir_name>] \-i <icon_name>
.br
.B q4wine-cli
\-p <prefix_name> \-b <windows_binary_path> [args]
.SH "DESCRIPTION"
q4wine-cli is part of the Q4Wine project. It provides a console interface to the Q4Wine database and its core functions.
.br
.SH "OPTIONS"
.RB "A summary of options is included below."
.TP
.BR "\-ps, \-\-procs"
output Wine process list for current prefix or for all prefixes and exit
.TP
.BR "\-p,  \-\-prefix"
sets the current prefix name
.TP
.BR "\-d,  \-\-dir"
sets the current directory name
.TP
.BR "\-i,  \-\-icon"
sets the current icon name
.TP
.BR "\-cd, \-\-cdimage"
sets the cd image name
.TP
.BR "\-b, \-\-binary"
sets the path to Windows binary for execute with current prefix settings
.TP
.BR "\-k,  \-\-kill"
sends \-9 term signal to current prefix process or for all prefixes processes
.TP
.BR "\-pl, \-\-prefixlist"
output all existing prefix names and exit
.TP
.BR "\-dl, \-\-dirlist"
output all existing dir names for current prefix and exit
.TP
.BR "\-il, \-\-iconlist"
output all existing icon names for current prefix/directory and exit
.TP
.BR "\-cl, \-\-cdlist"
output list of all cd images and exit
.TP
.BR "\-ml, \-\-mountlist"
output all mounted media for current prefix or all prefixes and exit
.TP
.BR "\-m,  \-\-mount"
mount a cd image or drive for current prefix and exit
.TP
.BR "\-u,  \-\-umount"
umount a cd image or drive for current prefix and exit
.TP
.BR "\-h,  \-\-help"
display help and exit
.TP
.BR "\-v,  \-\-version"
output version information and exit
.SH "EXIT STATUS"
.B 0
if OK or
.B \-1
if serious troubles
.SH "FILES"
.TP
.I /usr/bin/q4wine
The
.B Q4Wine
main gui program
.TP
.I /usr/bin/q4wine-cli
The
.B Q4Wine
command line interface program
.TP
.I /usr/bin/q4wine-helper
The
.B Q4Wine
runner helper program
.TP
.I /usr/lib/q4wine
Directory containing
.B Q4Wine's
shared libraries
.TP
.I $HOME/.config/q4wine
Directory containing Q4Wine config, icons, database and temporary files.

.SH "AUTHORS"
.SS Thanks to all:
Q4Wine is available thanks to the work of many to all people, who was
involved in the development process, testing, bugreporting, packaging or
translation creation. For a full listing of the authors, please see
the file
.B AUTHORS
in the top-level directory of the source distribution.

.SS Active developers:
.TP
Oleksii S. Malakhov (brezerk) <\fBbrezerk at gmail.com\fR>
Project maintainer, lead developer, web site designer and developer,
project documentation, support, etc. ;)

.TP
Sergey Skrypnic (opium) <\fBopium@jabber.com.ua\fR>
Website developer, hosting administration

.SS Inactive developers:
.TP
Pavel Zinin (pashazz) <\fBpzinin at gmail.com\fR>
Winetricks plugin developer

.TP
Dmitry Marakasov (amdmi3) <\fBamdmi3 at amdmi3.ru\fR>
FreeBSD support fixes

.SH "COPYRIGHT"
Q4Wine can be distributed under the terms of the GPLv3 license.
A copy of the license is in the file
.B LICENSE
in the top-level directory of the source distribution.

.SH "AVAILABILITY"
The most recent
.B public
version of wine can be downloaded from
.I http://q4wine.brezblock.org.ua/download/

The latest snapshot of the code may be obtained via
.B GIT
for information on how to do this, please see
.I http://q4wine.brezblock.org.ua/download/#git

Q4Wine, development headquarters, is at
.I http://q4wine.brezblock.org.ua
This website contains a great deal of information about Q4Wine.

.SH "BUGS"
If you find a bug in Q4Wine please report it to
<\fBbrezerk at gmail.com\fR> or directly to Q4Wine
bug tracker
.I https://sourceforge.net/projects/q4wine/
.PP
.SH "SEE ALSO"
.PP
\fBq4wine\fR(1),
\fBq4wine-helper\fR(1),
\fBwine\fR(1),
\fBwineserver\fR(1)\&
