######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 15 15:03:58 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . gui
INCLUDEPATH += . gui

# Input
HEADERS += gui/mainwindow.h
SOURCES += main.cpp gui/mainwindow.cpp
RESOURCES += k4wine.qrc
